version: "3.8"
services:
  guix:
    image: guix:${GUIX_VERSION}
    network_mode: bridge
    volumes:
      - "./build_channel:/build_channel"
      - "./build_env:/build_env"
    build:
      context: ./
      args:
        - GUIX_VERSION=${GUIX_VERSION}
    logging:
      options:
        max-size: 1m
        max-file: "3"
