version: "3.8"
services:
  guix-pack:
    image: guix-pack:${GUIX_VERSION}
    network_mode: bridge
    volumes:
      - "./output:/output"
    build:
      context: ./
      args:
        - GUIX_VERSION=${GUIX_VERSION}
    logging:
      options:
        max-size: 1m
        max-file: "3"
